[project]
name = "projeto-1-pos"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "argparse>=1.4.0",
    "datetime>=6.0",
    "jupyter>=1.1.1",
    "logging>=0.4.9.6",
    "pandas>=3.0.3",
    "pathlib>=1.0.1",
    "psycopg2>=2.9.12",
    "psycopg2-binary>=2.9.12",
    "python-dotenv>=1.2.2",
    "requests>=2.34.2",
    "sentence-transformers>=5.5.1",
    "sqlalchemy>=2.0.50",
]
